config:
  host: reddit.com/
  subreddit: r/

scripts:
  - name: subreddit.py
    host: reddit.com
    urls: 
      - name: popular
        url: /subreddits/popular
        fullUrl: https://www.reddit.com/subreddits/popular
    subreddits:
      - name: personalfinance
        jsonUrl: https://www.reddit.com/r/personalfinance.json